// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"GoProject/fudan_bbs/controller"
	"GoProject/fudan_bbs/internal/dao"
)

// Injectors from wire.go:

func InitApp() (*App, error) {
	db, err := dao.NewDB()
	if err != nil {
		return nil, err
	}
	daoDao, err := dao.NewDao(db)
	if err != nil {
		return nil, err
	}
	engine, err := controller.NewServer()
	if err != nil {
		return nil, err
	}
	app, err := NewApp(daoDao, engine)
	if err != nil {
		return nil, err
	}
	return app, nil
}
