[Server]
Addr = "localhost:10001"
ReadTimeout = 60
WriteTimeout = 60

[Database]
Dialect = "mysql"
User = "root"
Password = ""
Host = "localhost:3306"
Name = "forum"
Protocol = "tcp"
Charset = "utf8"
ParseTime = "True"
Loc = "Local"
MaxIdleConns = 10
MaxOpenConns = 100